# Assignment 4
## Description
In this assignment you must read in a file of metropolitan regions and associated sports teams from [assets/wikipedia_data.html](assets/wikipedia_data.html) and answer some questions about each metropolitan region. Each of these regions may have one or more teams from the "Big 4": NFL (football, in [assets/nfl.csv](assets/nfl.csv)), MLB (baseball, in [assets/mlb.csv](assets/mlb.csv)), NBA (basketball, in [assets/nba.csv](assets/nba.csv) or NHL (hockey, in [assets/nhl.csv](assets/nhl.csv)). Please keep in mind that all questions are from the perspective of the metropolitan region, and that this file is the "source of authority" for the location of a given sports team. Thus teams which are commonly known by a different area (e.g. "Oakland Raiders") need to be mapped into the metropolitan region given (e.g. San Francisco Bay Area). This will require some human data understanding outside of the data you've been given (e.g. you will have to hand-code some names, and might need to google to find out where teams are)!

For each sport I would like you to answer the question: **what is the win/loss ratio's correlation with the population of the city it is in?** Win/Loss ratio refers to the number of wins over the number of wins plus the number of losses. Remember that to calculate the correlation with [`pearsonr`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html), so you are going to send in two ordered lists of values, the populations from the wikipedia_data.html file and the win/loss ratio for a given sport in the same order. Average the win/loss ratios for those cities which have multiple teams of a single sport. Each sport is worth an equal amount in this assignment (20%\*4=80%) of the grade for this assignment. You should only use data **from year 2018** for your analysis -- this is important!

## Notes

1. Do not include data about the MLS or CFL in any of the work you are doing, we're only interested in the Big 4 in this assignment.
2. I highly suggest that you first tackle the four correlation questions in order, as they are all similar and worth the majority of grades for this assignment. This is by design!
3. It's fair game to talk with peers about high level strategy as well as the relationship between metropolitan areas and sports teams. However, do not post code solving aspects of the assignment (including such as dictionaries mapping areas to teams, or regexes which will clean up names).
4. There may be more teams than the assert statements test, remember to collapse multiple teams in one city into a single value!

## Question 1
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NHL** using **2018** data.

In [2]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nhl_df=pd.read_csv("assets/nhl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nhl_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

double_name = {
    'New York' : 'NewYork',
    'San Jose' : 'SanJose',
    'Los Angeles' : 'LosAngeles',
    'St. Louis' : 'St.Loius',
    'New Orleans' : 'NewOrleans',
    'New Jersey' : 'NewJersey',
    'Kansas City' : 'Kansas',
    'Salt Lake City' : 'SaltLake',
    'San Diego' : 'SanDiego',
    'San Antonio' :'SanAntonio',
    'Oklahoma City' : 'Oklahoma',
    'Tampa Bay' : 'TampaBay'
}

nhl_df = nhl_df[nhl_df['year'] == 2018]
cities = cities.rename(columns={'Population (2016 est.)[8]':'Population'})
nhl_df = nhl_df.replace(regex='.*Division.*', value=np.nan).dropna()
nhl_df['team'] = nhl_df['team'].str.replace('[*]', '')

for key in double_name:
    nhl_df['team'] = nhl_df['team'].str.replace(f'^{key}', f'{double_name[key]}')

nhl_df['city'] = nhl_df['team'].apply(str.split)
nhl_df['team_name'] =  list(map(lambda x : x[1] if len(x) == 2 else x[1] + ' ' + x[2], list(nhl_df['city'])))
nhl_df['city'] =  list(map(lambda x : x[0], list(nhl_df['city'])))

the_four = ['NFL', 'MLB', 'NBA', 'NHL']
    
cities = cities.applymap(str.strip)
for league in the_four:
    cities[league] = cities[league].str.replace('\[.*\]','')
    cities[league] = cities[league].str.replace('[a-z](?P<letter>[A-Z])', lambda x : '|' + x.group('letter'))
    cities[league] = cities[league].replace('—', np.nan)
    cities[league] = cities[league].replace('', np.nan)
    
    
# Little corner case =/
cities.iloc[13,2] = np.nan
    
cities_dict = {
    'City' : '',
    'Area' : '',
    '–.*' : '',
    ',.*' : '',
    '\s+' : ''
}
    
for key in cities_dict:
    cities['Metropolitan area'] = cities['Metropolitan area'].str.replace(f'{key}', f'{cities_dict[key]}')

new_cities = cities.set_index('Metropolitan area')
new_nhl_df = nhl_df.set_index('city')

merged = new_cities.join(new_nhl_df, how='left')
merged = merged[['Population', 'NHL', 'team', 'W', 'L', 'team_name']]
merged = merged[~merged['NHL'].isnull()]
merged

,Population,NHL,team,W,L,team_name
Boston,4794447,Bruins,Boston Bruins,50,20,Bruins
Buffalo,1132804,Sabres,Buffalo Sabres,25,45,Sabres
Calgary,1392609,Flames,Calgary Flames,37,35,Flames
Chicago,9512999,Blackhawks,Chicago Blackhawks,33,39,Blackhawks
Columbus,2041520,Blue Jackets,Columbus Blue Jackets,45,30,Blue Jackets
Dallas,7233323,Stars,Dallas Stars,42,32,Stars
Denver,2853077,Avalanche,NaN,NaN,NaN,NaN
Detroit,4297617,Red Wings,Detroit Red Wings,30,39,Red Wings
Edmonton,1321426,Oilers,Edmonton Oilers,36,40,Oilers
LasVegas,2155664,Golden Knights,NaN,NaN,NaN,NaN
LosAngeles,13310447,King|Ducks,LosAngeles Kings,45,29,Kings
Miami,6066387,Panthers,NaN,NaN,NaN,NaN
Minneapolis,3551036,Wild,NaN,NaN,NaN,NaN
Montreal,4098927,Canadiens,Montreal Canadiens,29,40,Canadiens
Nashville,1865298,Predators,Nashville Predators,53,18,Predators
NewYork,20153634,Ranger|Islander|Devils,NewYork Islanders,35,37,Islanders
NewYork,20153634,Ranger|Islander|Devils,NewYork Rangers,34,39,Rangers
Ottawa,1323783,Senators,Ottawa Senators,28,43,Senators
Philadelphia,6070500,Flyers,Philadelphia Flyers,42,26,Flyers
Phoenix,4661537,Coyotes,NaN,NaN,NaN,NaN
Pittsburgh,2342299,Penguins,Pittsburgh Penguins,47,29,Penguins
Raleigh,1302946,Hurricanes,NaN,NaN,NaN,NaN
SanFranciscoBay,6657982,Sharks,NaN,NaN,NaN,NaN
St.Louis,2807002,Blues,NaN,NaN,NaN,NaN
TampaBay,3032171,Lightning,TampaBay Lightning,54,23,Lightning
Toronto,5928040,Maple Leafs,Toronto Maple Leafs,49,26,Maple Leafs
Vancouver,2463431,Canucks,Vancouver Canucks,31,40,Canucks
Washington,6131977,Capitals,Washington Capitals,49,26,Capitals
Winnipeg,778489,Jets,Winnipeg Jets,52,20,Jets

In [95]:
cities

,Metropolitan area,Population,NFL,MLB,NBA,NHL
0,NewYork,20153634,Giant|Jets,Yankee|Mets,Knick|Nets,Ranger|Islander|Devils
1,LosAngeles,13310447,Ram|Chargers,Dodger|Angels,Laker|Clippers,King|Ducks
2,SanFranciscoBay,6657982,49er|Raiders,Giant|Athletics,Warriors,Sharks
3,Chicago,9512999,Bears,Cub|White Sox,Bulls,Blackhawks
4,Dallas,7233323,Cowboys,Rangers,Mavericks,Stars
5,Washington,6131977,Redskins,Nationals,Wizards,Capitals
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers
7,Boston,4794447,Patriots,Red Sox,Celtics,Bruins
8,Minneapolis,3551036,Vikings,Twins,Timberwolves,Wild
9,Denver,2853077,Broncos,Rockies,Nuggets,Avalanche
10,Miami,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers,Pistons,Red Wings
13,Toronto,5928040,NaN,Blue Jays,Raptors,Maple Leafs
14,Houston,6772470,Texans,Astros,Rockets,NaN
15,Atlanta,5789700,Falcons,Braves,Hawks,NaN
16,TampaBay,3032171,Buccaneers,Rays,NaN,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,NaN,Penguins
18,Cleveland,2055612,Browns,Indians,Cavaliers,NaN
19,Seattle,3798902,Seahawks,Mariners,NaN,NaN
20,Cincinnati,2165139,Bengals,Reds,NaN,NaN
21,Kansas,2104509,Chiefs,Royals,NaN,NaN
22,St.Louis,2807002,NaN,Cardinals,NaN,Blues
23,Baltimore,2798886,Ravens,Orioles,NaN,NaN
24,Charlotte,2474314,Panthers,NaN,Hornets,NaN
25,Indianapolis,2004230,Colts,NaN,Pacers,NaN
26,Nashville,1865298,Titans,NaN,NaN,Predators
27,Milwaukee,1572482,NaN,Brewers,Bucks,NaN
28,NewOrleans,1268883,Saints,NaN,Pelicans,NaN
29,Buffalo,1132804,Bills,NaN,NaN,Sabres
30,Montreal,4098927,NaN,NaN,NaN,Canadiens
31,Vancouver,2463431,NaN,NaN,NaN,Canucks
32,Orlando,2441257,NaN,NaN,Magic,NaN
33,Portland,2424955,NaN,NaN,Trail Blazers,NaN
34,Columbus,2041520,NaN,NaN,NaN,Blue Jackets
35,Calgary,1392609,NaN,NaN,NaN,Flames
36,Ottawa,1323783,NaN,NaN,NaN,Senators
37,Edmonton,1321426,NaN,NaN,NaN,Oilers
38,SaltLake,1186187,NaN,NaN,Jazz,NaN
39,Winnipeg,778489,NaN,NaN,NaN,Jets
40,SanDiego,3317749,NaN,Padres,NaN,NaN
41,SanAntonio,2429609,NaN,NaN,Spurs,NaN
42,Sacramento,2296418,NaN,NaN,Kings,NaN
43,LasVegas,2155664,NaN,NaN,NaN,Golden Knights
44,Jacksonville,1478212,Jaguars,NaN,NaN,NaN
45,Oklahoma,1373211,NaN,NaN,Thunder,NaN
46,Memphis,1342842,NaN,NaN,Grizzlies,NaN
47,Raleigh,1302946,NaN,NaN,NaN,Hurricanes
48,GreenBay,318236,Packers,NaN,NaN,NaN
49,Hamilton,747545,NaN,NaN,NaN,NaN
50,Regina,236481,NaN,NaN,NaN,NaN

## Question 2
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NBA** using **2018** data.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nba_df=pd.read_csv("assets/nba.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nba_correlation():
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

    return stats.pearsonr(population_by_region, win_loss_by_region)

## Question 3
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **MLB** using **2018** data.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("assets/mlb.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def mlb_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
    assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"

    return stats.pearsonr(population_by_region, win_loss_by_region)

## Question 4
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NFL** using **2018** data.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nfl_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from nfl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
    assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"

    return stats.pearsonr(population_by_region, win_loss_by_region)

## Question 5
In this question I would like you to explore the hypothesis that **given that an area has two sports teams in different sports, those teams will perform the same within their respective sports**. How I would like to see this explored is with a series of paired t-tests (so use [`ttest_rel`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html)) between all pairs of sports. Are there any sports where we can reject the null hypothesis? Again, average values where a sport has multiple teams in one region. Remember, you will only be including, for each sport, cities which have teams engaged in that sport, drop others as appropriate. This question is worth 20% of the grade for this assignment.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("assets/mlb.csv")
nhl_df=pd.read_csv("assets/nhl.csv")
nba_df=pd.read_csv("assets/nba.csv")
nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def sports_team_performance():
    # YOUR CODE HERE
    raise NotImplementedError()
    
    # Note: p_values is a full dataframe, so df.loc["NFL","NBA"] should be the same as df.loc["NBA","NFL"] and
    # df.loc["NFL","NFL"] should return np.nan
    sports = ['NFL', 'NBA', 'NHL', 'MLB']
    p_values = pd.DataFrame({k:np.nan for k in sports}, index=sports)
    
    assert abs(p_values.loc["NBA", "NHL"] - 0.02) <= 1e-2, "The NBA-NHL p-value should be around 0.02"
    assert abs(p_values.loc["MLB", "NFL"] - 0.80) <= 1e-2, "The MLB-NFL p-value should be around 0.80"
    return p_values